apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Release.Namespace }}.env.my`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend-service
          port: 3000
