frontend:
  image: chengyinwu/frontend
  tag: '04e9015'
  autoscaling:
    averageUtilization: 90
backend:
  image: chengyinwu/backend
  tag: '04e9015'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
