frontend:
  image: ccr.ccs.tencentyun.com/app-public/frontend
  tag: 2894cf6
  autoscaling:
    averageUtilization: 90
backend:
  image: ccr.ccs.tencentyun.com/app-public/backend
  tag: 2894cf6
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
