frontend:
  image: ccr.ccs.tencentyun.com/app-public/frontend
  tag: latest
  autoscaling:
    averageUtilization: 50

backend:
  image: ccr.ccs.tencentyun.com/app-public/backend
  tag: latest
  autoscaling:
    averageUtilization: 50

database:
  enabled: false
  uri: 10.10.10.10
  username: external_postgres
  password: external_postgres
